// Code generated by protoc-gen-go-mongo. DO NOT EDIT.
// versions:
// - protoc-gen-go-mongo v0.0.1
// - protoc              v5.27.1
// source: internal/examples/data.proto

package examples

import grpc "google.golang.org/grpc"

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataFieldData_Id
// DataFieldData_BoolValue
// DataFieldData_BoolProtoValue
// DataFieldData_BytesValue
// DataFieldData_BytesProtoValue
// DataFieldData_DoubleValue
// DataFieldData_DoubleProtoValue
// DataFieldData_FloatValue
// DataFieldData_FloatProtoValue
// DataFieldData_Int32Value
// DataFieldData_Int32ProtoValue
// DataFieldData_Int64Value
// DataFieldData_Int64ProtoValue
// DataFieldData_StringValue
// DataFieldData_StringProtoValue
// DataFieldData_Uint32Value
// DataFieldData_Uint32ProtoValue
// DataFieldData_Uint64Value
// DataFieldData_Uint64ProtoValue
// DataFieldData_Timestamp
